name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake build-essential
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)